on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 6 * * *'
  workflow_dispatch:

name: Export

jobs:
  export:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'export'

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            github::tux2000/comprate

      - name: Export json
        run: |
          comprate::export_json(c(90, 365, 2*365), "data.json")
        shell: Rscript {0}

      - name: Commit and Push export
        run: |
          git config --global user.name 'Tux2000'
          git config --global user.email 'tux2000@users.noreply.github.com'
          git commit -am "Automated export"
          git push
